<h1>PHP authentication</h1>
<p>Please log in with you username and password below.</p>
<form action="?" method="POST">
<label for="username">Username:</label>
	<input type="text" name="username" id="username" maxlength="20" size="20" /><br/>
<label for="password">Password:</label>
	<input type="password" name="password" id="password" maxlength="20" size="20" /><br/>
<input type="submit" />

</form>
